
const translation = {
  en: {
    errorConsumption: 'Error trying to get consumption info',
    errorDisk: 'Error trying to load storage information',
    errorDevices: 'Error trying to load devices information',
    errorGroups: 'Error trying to load groups information',
    errorNotifications: 'Error trying to get notifications',
    errorDetails: 'Error trying to load consumption details',
    Today: 'Today',
    Week: 'Week',
    Monday: 'Monday',
    Month: 'Month',
    Year: 'Year',
    used: 'ocupado',
    free: 'disponível',
    Used: 'Used',
    Free: 'Free',
    Online: 'Online',
    Offline: 'Offline',
    Registered: 'Registered',
    NotRegistered: 'Not registered',
    Unconfigured: 'Unconfigured',
    ShowAll: 'Show All',
    Search: 'SEARCH',
    Date: 'Date',
    Cost: 'Cost',
    Server: 'Server',
    DiskUsage: 'DISK USAGE',
    UsedSpace: 'Used Space',
    Available: 'Available',
    Groups: 'Groups',
    TotalRegistered: 'Total of devices registered',
    Subgroups: 'Subgroups',
    Devices: 'Devices',
    Notifications: 'Notifications',
    notifications: 'notifications',
    January: 'January',
    February: 'February',
    March: 'March',
    April: 'April',
    May: 'May',
    June: 'June',
    July: 'July',
    August: 'August',
    September: 'September',
    October: 'October',
    November: 'November',
    December: 'December',
  },
  pt: {
    errorConsumption: 'Erro ao tentar obter as informações de consumo',
    errorDisk: 'Erro ao tentar carregar informações de armazenamento',
    errorDevices: 'Erro ao tentar carregar informações de dispositivos',
    errorGroups: 'Erro ao tentar carregar informações de grupos',
    errorNotifications: 'Erro ao tentar obter as notificações',
    errorDetails: 'Erro ao tentar obter detalhes do consumo',
    Today: 'Hoje',
    Week: 'Semana',
    Monday: 'Segunda-Feira',
    Month: 'Mês',
    Year: 'Ano',
    Used: 'Ocupado',
    used: 'ocupado',
    Free: 'Livre',
    free: 'livre',
    Online: 'Online',
    Offline: 'Offline',
    Registered: 'Registrado',
    NotRegistered: 'Não registrado',
    Unconfigured: 'Não configurado',
    ShowAll: 'Mostrar Tudo',
    Search: 'BUSCAR',
    Date: 'Data',
    Cost: 'Custo',
    Server: 'Servidor',
    TotalRegistered: 'Total de dispositivos registrados',
    Subgroups: 'Subgrupos',
    Notifications: 'Notificações',
    notifications: 'notificações',
    DiskUsage: 'USO DE DISO',
    UsedSpace: 'Ocupado',
    Available: 'Disponível',
    Devices: 'Dispositivos',
    Groups: 'Grupos',
    January: 'Janeiro',
    February: 'Fevereiro',
    March: 'Março',
    April: 'Abril',
    May: 'Maio',
    June: 'Junho',
    July: 'Julho',
    August: 'Agosto',
    September: 'Setembro',
    October: 'Outubro',
    November: 'Novembro',
    December: 'Dezembro',
  }
}

export default translation;