
const translation = {
  en: {
    Search: 'Search',
    Readings: 'Readings',
    Info: 'Info',
    Settings: 'Settings',
    Relay: 'Relay',
    errorDevice: 'Error trying to load device',
    Device: 'Device',
    title: 'Device',
    Consumption: 'Consumption',
    Current: 'Current',
    Demand: 'Demand',
    Power: 'Active Power',
    Day: 'Day',
    Week: 'Week',
    Month: 'Month',
    Year: 'Year',
    Average: 'Average',
    Total: 'Total',
    PhaseA: 'Phase A',
    PhaseB: 'Phase B',
    PhaseC: 'Phase C',
    errorOcurred: 'An error occurred',
    errorConnect: 'Unable to connect to server',
    invalidSearch: 'Invalid search',
    errorUnexpected: 'An unexpected error occurred',
    invalidId: 'Invalid ID',
    noData: 'There is no data for this search',
    to: 'to',
    OnlineTime: 'Online time',
    Parameter: 'Parameter',
    Period: 'Period',
    Date: 'Date',
    Start: 'Start',
    SearchButton: 'SEARCH',
    Highest: 'Highest',
    Lowest: 'Lowest',
    Selected: 'Selected',
    Time: 'Time',
    January: 'January',
    February: 'February',
    March: 'March',
    April: 'April',
    May: 'May',
    June: 'June',
    July: 'July',
    August: 'August',
    September: 'September',
    October: 'October',
    November: 'November',
    December: 'December',

    Devices: 'Devices',
    Groups: 'Groups',
    nameRequired: 'Report name required',
    paramRequired: 'No parameter selected',
    errorDevices: 'Error loading devices',
    creating: 'Creating report...',
    reportFail: 'Report creation has failed',
    noReports: 'No reports have been found',
    errorReports: 'Error loading reports',
    reportDeleted: 'Report has been deleted',
    errorDelete: 'Error trying to delete report',
    errorDownload: 'Error trying to download report',
    Select: 'Select device or group',
    Cancel: 'Cancel',
    Add: 'Add',
    reportName: 'Report name',
    selectParameter: 'Select parameter',
    createReport: 'Create Report',
    Ready: 'Ready',
    Pending: 'Pending',
    Processing: 'Processing',
    Error: 'Error',
    Undefined: 'Undefined',
    notificationError: `Notification could not be sent`,
    deviceSuccess: 'Device created',
    errorCreate: 'Error trying to create device',
    errorName: 'Device name already exists',
    noDevices: 'No devices',
    Active: 'Active',
    Inactive: 'Inactive',
    filter: 'filter',
    Filter: 'Filter',
    SelectGroup: 'Select a group',
    All: 'ALL',
    On: 'ON',
    Off: 'OFF',
    RemoveFilter: 'REMOVE FILTER',
    NewDevice: 'New Device',
    DeviceName: 'Device name',
    Register: 'Register',
    ShowResults: 'Showing results for',
    SeeGroup: 'See group',
    DisableSchedules: 'Disable schedules',
    SchedulesDisabled: 'Schedules disabled',
  },
  pt: {
    Search: 'Busca',
    Readings: 'Leituras',
    Info: 'Informações',
    Settings: 'Configurações',
    Relay: 'Relé',
    errorDevice: 'Erro ao carregar os dispositivo',
    Device: 'Dispositivo',
    title: 'Dispositivo',
    Consumption: 'Consumo',
    Current: 'Corrente',
    Demand: 'Demanda',
    Power: 'Potência Ativa',
    Day: 'Dia',
    Week: 'Semana',
    Month: 'Mês',
    Year: 'Ano',
    Total: 'Total',
    PhaseA: 'Fase A',
    PhaseB: 'Fase B',
    PhaseC: 'Fase C',
    Average: 'Média',
    errorOcurred: 'Ocorreu um erro',
    errorConnect: 'Erro na conexão com o servidor',
    invalidSearch: 'Busca inválida',
    errorUnexpected: 'Um erro inesperado aconteceu',
    invalidId: 'ID inválido',
    noData: 'Não há dados para essa busca',
    to: 'a',
    OnlineTime: 'Tempo online',
    Parameter: 'Parâmetro',
    Period: 'Período',
    Date: 'Data',
    Start: 'Inicial',
    SearchButton: 'BUSCAR',
    Highest: 'Maior',
    Lowest: 'Menor',
    Selected: 'Selecionado',
    Time: 'Tempo',
    January: 'Janeiro',
    February: 'Fevereiro',
    March: 'Março',
    April: 'Abril',
    May: 'Maio',
    June: 'Junho',
    July: 'Julho',
    August: 'Agosto',
    September: 'Setembro',
    October: 'Outubro',
    November: 'Novembro',
    December: 'Dezembro',

    Devices: 'Dispositivos',
    Groups: 'Grupos',
    nameRequired: 'O nome do relatório é obrigatório',
    paramRequired: 'Nenhum parâmetro selecionado',
    errorDevices: 'Erro ao carregar os dispositivos',
    creating: 'Criando relatório...',
    reportFail: 'Falha na criação de relatório',
    noReports: 'Nenhum relatório foi encontrado',
    errorReports: 'Erro ao carregar os relatórios',
    reportDeleted: 'O relatório foi excluído',
    errorDelete: 'Erro ao tentar excluir o relatório',
    errorDownload: 'Erro ao tentar baixar o relatório',
    Select: 'Selecionar',
    Cancel: 'Cancelar',
    Add: 'Adicionar',
    reportName: 'Nome do relatório',
    selectParameter: 'Selecionar parâmetro',
    createReport: 'Criar relatório',
    Ready: 'Pronto',
    Pending: 'Pendente',
    Processing: 'Processando',
    Error: 'Erro',
    Undefined: 'Indefinido',
    notificationError: `A notificação não pôde ser enviada`,
    deviceSuccess: 'Dispositivo criado',
    errorCreate: 'Erro ao tentar criar dispositivo',
    errorName: 'Esse nome de dispositivo já existe',
    noDevices: 'Nenhum dispositivo encontrado',
    Active: 'Ativo',
    Inactive: 'Inativo',
    filter: 'filtro',
    Filter: 'Filtro',
    SelectGroup: 'Selecione um grupo',
    All: 'TODOS',
    On: 'ON',
    Off: 'OFF',
    RemoveFilter: 'REMOVER FILTRO',
    NewDevice: 'Novo Dispositivo',
    DeviceName: 'Nome do dispositivo',
    Register: 'Registrar',
    ShowResults: 'Mostrando resultados para',
    SeeGroup: 'Ver grupo',
    DisableSchedules: 'Desabilitar agendamentos',
    SchedulesDisabled: 'Agendamentos desabilitados',
  }
}

export default translation;