
const translation = {
  en: {
    notificationError: `Notification could not be sent`,
    deviceSuccess: 'Device created',
    errorCreate: 'Error trying to create device',
    errorDevices: 'Error trying to load devices',
    errorConnect: 'Unable to connect to server',
    errorName: 'Device name already exists',
    errorUnexpected: 'An unexpected error occurred',
    nameRequired: 'Device name is required',
    noDevices: 'No devices',
    title: 'Devices',
    Devices: 'Devices',
    Active: 'Active',
    Inactive: 'Inactive',
    filter: 'filter',
    Filter: 'Filter',
    SelectGroup: 'Select a group',
    All: 'ALL',
    On: 'ON',
    Off: 'OFF',
    RemoveFilter: 'REMOVE FILTER',
    Cancel: 'Cancel',
    NewDevice: 'New Device',
    DeviceName: 'Device name',
    Register: 'Register',
    Relay: 'Relay',
    ShowResults: 'Showing results for',
    SeeGroup: 'See group',
    DisableSchedules: 'Disable schedules',
    SchedulesDisabled: 'Schedules disabled',
  },
  pt: {
    notificationError: `A notificação não pôde ser enviada`,
    deviceSuccess: 'Dispositivo criado',
    errorCreate: 'Erro ao tentar criar dispositivo',
    errorDevices: 'Erro ao carregar os dispositivos',
    errorConnect: 'Erro na conexão com o servidor',
    errorName: 'Esse nome de dispositivo já existe',
    errorUnexpected: 'Um erro inesperado aconteceu',
    nameRequired: 'O nome do dispositivo é obrigatório',
    noDevices: 'Nenhum dispositivo encontrado',
    title: 'Dispositivos',
    Devices: 'Dispositivos',
    Active: 'Ativo',
    Inactive: 'Inativo',
    filter: 'filtro',
    Filter: 'Filtro',
    SelectGroup: 'Selecione um grupo',
    All: 'TODOS',
    On: 'ON',
    Off: 'OFF',
    RemoveFilter: 'REMOVER FILTRO',
    Cancel: 'Cancelar',
    NewDevice: 'Novo Dispositivo',
    DeviceName: 'Nome do dispositivo',
    Register: 'Registrar',
    Relay: 'Relé',
    ShowResults: 'Mostrando resultados para',
    SeeGroup: 'Ver grupo',
    DisableSchedules: 'Desabilitar agendamentos',
    SchedulesDisabled: 'Agendamentos desabilitados',
  }
}

export default translation;