
const translation = {
  en: {
    Consumption: 'Consumption',
    Current: 'Current',
    Demand: 'Demand',
    Power: 'Power',
    Devices: 'Devices',
    Total: 'Total',
    PhaseA: 'Phase A',
    PhaseB: 'Phase B',
    PhaseC: 'Phase C',
    Average: 'Average',
    errorDevices: 'Error loading devices',
    errorComparatives: 'Error loading comparatives',
    title: 'Comparatives',
    Period: 'Period',
    Day: 'Day',
    Month: 'Month',
    AddDevice: 'Add Device',
    AddDevices: 'Add Devices',
    Cancel: 'Cancel',
    Add: 'Add',
    CurrentDevices: 'Current devices',
  },
  pt: {
    Consumption: 'Consumo',
    Current: 'Corrente',
    Demand: 'Demanda',
    Power: 'Potência',
    Devices: 'Dispositivos',
    Total: 'Total',
    PhaseA: 'Fase A',
    PhaseB: 'Fase B',
    PhaseC: 'Fase C',
    Average: 'Média',
    errorDevices: 'Erro ao carregar os dispositivos',
    errorComparatives: 'Erro ao carregar os comparativos',
    title: 'Comparativos',
    Period: 'Período',
    Day: 'Dia',
    Month: 'Mês',
    AddDevice: 'Adicionar Dispositivo',
    AddDevices: 'Adicionar Dispositivos',
    Cancel: 'Cancelar',
    Add: 'Adicionar',
    CurrentDevices: 'Dispositivos atuais',
  }
}

export default translation;