
const translation = {
  en: {
    Devices: 'Devices',
    Groups: 'Groups',
    Consumption: 'Consumption',
    Current: 'Current',
    Demand: 'Demand',
    Power: 'Active Power',
    nameRequired: 'Report name required',
    paramRequired: 'No parameter selected',
    errorDevices: 'Error loading devices',
    creating: 'Creating report...',
    reportFail: 'Report creation has failed',
    noReports: 'No reports have been found',
    errorReports: 'Error loading reports',
    reportDeleted: 'Report has been deleted',
    errorDelete: 'Error trying to delete report',
    errorDownload: 'Error trying to download report',
    title: 'Reports',
    Period: 'Period',
    Day: 'Day',
    Month: 'Month',
    Select: 'Select device or group',
    Cancel: 'Cancel',
    Add: 'Add',
    reportName: 'Report name',
    selectParameter: 'Select parameter',
    createReport: 'Create Report',
    Ready: 'Ready',
    Pending: 'Pending',
    Processing: 'Processing',
    Error: 'Error',
    Undefined: 'Undefined',
  },
  pt: {
    Devices: 'Dispositivos',
    Groups: 'Grupos',
    Consumption: 'Consumo',
    Current: 'Corrente',
    Demand: 'Demanda',
    Power: 'Potência Ativa',
    nameRequired: 'O nome do relatório é obrigatório',
    paramRequired: 'Nenhum parâmetro selecionado',
    errorDevices: 'Erro ao carregar os dispositivos',
    creating: 'Criando relatório...',
    reportFail: 'Falha na criação de relatório',
    noReports: 'Nenhum relatório foi encontrado',
    errorReports: 'Erro ao carregar os relatórios',
    reportDeleted: 'O relatório foi excluído',
    errorDelete: 'Erro ao tentar excluir o relatório',
    errorDownload: 'Erro ao tentar baixar o relatório',
    title: 'Relatórios',
    Period: 'Período',
    Day: 'Dia',
    Month: 'Mês',
    Select: 'Selecionar',
    Cancel: 'Cancelar',
    Add: 'Adicionar',
    reportName: 'Nome do relatório',
    selectParameter: 'Selecionar parâmetro',
    createReport: 'Criar relatório',
    Ready: 'Pronto',
    Pending: 'Pendente',
    Processing: 'Processando',
    Error: 'Erro',
    Undefined: 'Indefinido',
  }
}

export default translation;