
const translation = {
  en: {
    Search: 'Search',
    Settings: 'Settings',
    Info: 'Info',
    errorGroup: 'Error trying to load group',
    title: 'Group',
    invalidSubgroup: 'Invalid subgroup',
    TotalConsumption: 'Total Consumption',
    Subgroup: 'Subgroup',
    Details: 'Details',
    deviceRemovedSuccess: 'Device removed',
    deviceRemovedError: 'Error trying to remove device',
    subgroupCreate: 'Subgroup created',
    errorCreateSubgroup: 'Error trying to create subgroup',
    errorNameSub: 'Subgroup name already exists',
    nameRequiredSub: 'Subgroup name is required',
    errorSubs: 'Error trying to load subgroups',
    noSubs: 'No subgroups have been found',
    SelectSubgroup: 'Select a subgroup',
    NewSub: 'New Subgroup',
    subName: 'Subgroup name',
    EditSub: 'Edit Subgroup',

    Readings: 'Readings',
    Relay: 'Relay',
    Device: 'Device',
    Consumption: 'Consumption',
    Current: 'Current',
    Demand: 'Demand',
    Power: 'Active Power',
    Day: 'Day',
    Week: 'Week',
    Month: 'Month',
    Year: 'Year',
    Average: 'Average',
    Total: 'Total',
    PhaseA: 'Phase A',
    PhaseB: 'Phase B',
    PhaseC: 'Phase C',
    errorOcurred: 'An error occurred',
    errorConnect: 'Unable to connect to server',
    invalidSearch: 'Invalid search',
    errorUnexpected: 'An unexpected error occurred',
    invalidId: 'Invalid ID',
    noData: 'There is no data for this search',
    to: 'to',
    OnlineTime: 'Online time',
    Parameter: 'Parameter',
    Period: 'Period',
    Date: 'Date',
    Start: 'Start',
    SearchButton: 'SEARCH',
    Highest: 'Highest',
    Lowest: 'Lowest',
    Selected: 'Selected',
    Time: 'Time',
    January: 'January',
    February: 'February',
    March: 'March',
    April: 'April',
    May: 'May',
    June: 'June',
    July: 'July',
    August: 'August',
    September: 'September',
    October: 'October',
    November: 'November',
    December: 'December',
    notificationError: `Notification could not be sent`,
    updateSuccess: 'The changes have been saved',
    updateError: 'Error trying to save changes',
    deleteSucces: 'The group has been removed',
    deleteError: 'Error trying to delete device',
    Cancel: 'Cancel',
    Save: 'Save',
    Edit: 'Edit',
    DeleteGroupButton: 'DELETE GROUP',
    DeleteGroup: 'Delete Group',
    ConfirmDelete: 'Are you sure you want to delete this group?',
    Delete: 'Delete',
    Description: 'DESCRIPTION',
    AddedSubgroup: 'Added to the subgroup',
    RelayOption: 'The relay option is',
    enabled: 'enabled',
    disabled: 'disabled',
    clickTo: 'Click to',
    disable: 'disable',
    enable: 'enable',
    Switchboard: 'Electrical Switchboard',
    NominalCUrrent: 'Nominal Current',
    RatedVoltage: 'Nominal Voltage',
    CurrentTransformer: 'Transformer Current',
    Phase: 'Phases',
    Diameter: 'Diameter',
    FrameVoltage: 'Switchboard Voltage',
    IDLora: 'ID Lora',
    MacAddress: 'Mac Address',
    LimitValues: 'LIMIT VALUES',
    
    Subgroups: 'Subgroups',
    errorCreate: 'Error trying to create group',
    deviceSuccess: 'Group created',
    errorName: 'Group name already exists',
    noDevices: 'No groups',
    nameRequired: 'Group name is required',
    errorDevices: 'Error trying to load groups',
    NewDevice: 'New Group',
    DeviceName: 'Group name',
    Register: 'Register',
    ShowResults: 'Showing results for',

    Devices: 'Devices',
    Groups: 'Groups',
    paramRequired: 'No parameter selected',
    creating: 'Creating report...',
    reportFail: 'Report creation has failed',
    noReports: 'No reports have been found',
    errorReports: 'Error loading reports',
    reportDeleted: 'Report has been deleted',
    errorDelete: 'Error trying to delete report',
    errorDownload: 'Error trying to download report',
    Select: 'Select device or group',
    Add: 'Add',
    reportName: 'Report name',
    selectParameter: 'Select parameter',
    createReport: 'Create Report',
    Ready: 'Ready',
    Pending: 'Pending',
    Processing: 'Processing',
    Error: 'Error',
    Undefined: 'Undefined',
    Active: 'Active',
    Inactive: 'Inactive',
    filter: 'filter',
    Filter: 'Filter',
    SelectGroup: 'Select a group',
    All: 'ALL',
    On: 'ON',
    Off: 'OFF',
    RemoveFilter: 'REMOVE FILTER',
    SeeGroup: 'See group',
    DisableSchedules: 'Disable schedules',
    SchedulesDisabled: 'Schedules disabled',
  },
  pt: {
    Search: 'Busca',
    Info: 'Informações',
    Settings: 'Configurações',
    errorGroup: 'Erro ao carregar grupo',
    title: 'Grupo',
    invalidSubgroup: 'Subgrupo inválido',
    TotalConsumption: 'Consumo total',
    Subgroup: 'Subgrupo',
    Details: 'Details',
    deviceRemovedSuccess: 'Dispositivo removido',
    deviceRemovedError: 'Erro ao tentar remover dispositivo',
    subgroupCreate: 'Subgrupo criado',
    errorCreateSubgroup: 'Erroao tentar criar subgrupo',
    errorNameSub: 'Esse nome de subgrupo já existe',
    nameRequiredSub: 'O nome do subgrupo é obrigatório',
    errorSubs: 'Erro ao carregar os subgrupos',
    noSubs: 'Nenhum subgrupo foi encontrado',
    SelectSubgroup: 'Selecione um subgrupo',
    NewSub: 'Novo Subgrupo',
    subName: 'Nome do subrupo',
    EditSub: 'Editar Subgrupo',

    Readings: 'Leituras',
    Relay: 'Relé',
    Device: 'Dispositivo',
    Consumption: 'Consumo',
    Current: 'Corrente',
    Demand: 'Demanda',
    Power: 'Potência Ativa',
    Day: 'Dia',
    Week: 'Semana',
    Month: 'Mês',
    Year: 'Ano',
    Total: 'Total',
    PhaseA: 'Fase A',
    PhaseB: 'Fase B',
    PhaseC: 'Fase C',
    Average: 'Média',
    errorOcurred: 'Ocorreu um erro',
    errorConnect: 'Erro na conexão com o servidor',
    invalidSearch: 'Busca inválida',
    errorUnexpected: 'Um erro inesperado aconteceu',
    invalidId: 'ID inválido',
    noData: 'Não há dados para essa busca',
    to: 'a',
    OnlineTime: 'Tempo online',
    Parameter: 'Parâmetro',
    Period: 'Período',
    Date: 'Data',
    Start: 'Inicial',
    SearchButton: 'BUSCAR',
    Highest: 'Maior',
    Lowest: 'Menor',
    Selected: 'Selecionado',
    Time: 'Tempo',
    January: 'Janeiro',
    February: 'Fevereiro',
    March: 'Março',
    April: 'Abril',
    May: 'Maio',
    June: 'Junho',
    July: 'Julho',
    August: 'Agosto',
    September: 'Setembro',
    October: 'Outubro',
    November: 'Novembro',
    December: 'Dezembro',
    notificationError: `A notificação não pôde ser enviada`,
    updateSuccess: 'As alterações foram salvas',
    updateError: 'Erro ao tentar salvar as alterações',
    deleteSucces: 'O grupo foi removido',
    deleteError: 'Erro ao tentar remover o dispositivo',
    Cancel: 'Cancelar',
    Save: 'Salvar',
    Edit: 'Editar',
    DeleteGroupButton: 'DELETAR',
    DeleteGroup: 'Deletar grupo',
    ConfirmDelete: 'Você tem certeza que deseja remover esse grupo?',
    Delete: 'Deletar',
    Description: 'DESCRIÇÃO',
    AddedSubgroup: 'Adicionado ao subgrupo',
    RelayOption: 'A opção de relé está',
    enabled: 'habilitada',
    disabled: 'desabilitada',
    clickTo: 'Clique para',
    disable: 'desabilitar',
    enable: 'habilitar',
    Switchboard: 'Quadro elétrico',
    NominalCUrrent: 'Corrente Nominal',
    RatedVoltage: 'Tensão Nominal',
    CurrentTransformer: 'Corrente do Transformador',
    Phase: 'Fases',
    Diameter: 'Diâmetro',
    FrameVoltage: 'Tensão do Quadro',
    IDLora: 'ID Lora',
    MacAddress: 'Mac Address',
    LimitValues: 'VALORES LIMITES',

    Subgroups: 'Subgrupos',
    nameRequired: 'O nome do grupo é obrigatório',
    errorDevices: 'Erro ao carregar os grupos',
    deviceSuccess: 'Grupo criado',
    errorCreate: 'Erro ao tentar criar grupo',
    errorName: 'Esse nome de grupo já existe',
    noDevices: 'Nenhum grupo encontrado',
    NewDevice: 'Novo Grupo',
    DeviceName: 'Nome do grupo',
    Register: 'Registrar',
    ShowResults: 'Mostrando resultados para',

    Devices: 'Dispositivos',
    Groups: 'Grupos',
    paramRequired: 'Nenhum parâmetro selecionado',
    creating: 'Criando relatório...',
    reportFail: 'Falha na criação de relatório',
    noReports: 'Nenhum relatório foi encontrado',
    errorReports: 'Erro ao carregar os relatórios',
    reportDeleted: 'O relatório foi excluído',
    errorDelete: 'Erro ao tentar excluir o relatório',
    errorDownload: 'Erro ao tentar baixar o relatório',
    Select: 'Selecionar',
    Add: 'Adicionar',
    reportName: 'Nome do relatório',
    selectParameter: 'Selecionar parâmetro',
    createReport: 'Criar relatório',
    Ready: 'Pronto',
    Pending: 'Pendente',
    Processing: 'Processando',
    Error: 'Erro',
    Undefined: 'Indefinido',
    Active: 'Ativo',
    Inactive: 'Inativo',
    filter: 'filtro',
    Filter: 'Filtro',
    SelectGroup: 'Selecione um grupo',
    All: 'TODOS',
    On: 'ON',
    Off: 'OFF',
    RemoveFilter: 'REMOVER FILTRO',
    SeeGroup: 'Ver grupo',
    DisableSchedules: 'Desabilitar agendamentos',
    SchedulesDisabled: 'Agendamentos desabilitados',
  }
}

export default translation;