
const translation = {
  en: {
    title: 'Notifications',
    errorNotifications: 'Error trying to get notifications',
    deleteSuccess: 'Notifications have been deleted',
    deleteError: 'Error trying to delete notifications',
    noNotifications: 'No notifications have been found',
    selectAll: 'Select All',
    deleteSelected: 'Delete selected',
    generatedBy: 'Generated by',
  },
  pt: {
    title: 'Notificações',
    errorNotifications: 'Erro ao tentar obter as notificações',
    deleteSuccess: 'As notificações foram deletadas',
    deleteError: 'Erro ao tentar deletar as notificações',
    noNotifications: 'Nenhuma notificação foi encontrada',
    selectAll: 'Selecionar todas',
    deleteSelected: 'Excluir selecionadas',
    generatedBy: 'Gerada por'
  }
}

export default translation;